Spectral averaging with outlier rejection
bittremieux/falcon pull request #28
Opened 2024-10-25 12:12 UTC by Janne98

Add option to choose consensus spectrum method by setting `--consensus_method` to `medoid` or `average`. If `average`, [spectral averaging with outlier rejection](https://doi.org/10.1002/pmic.202300234) will be performed.

2024-11-05 07:24 UTC, bittremieux commented
@Janne98 Can you first make sure that merge conflicts are resolved?

2024-11-05 10:50 UTC, Janne98 commented
> @Janne98 Can you first make sure that merge conflicts are resolved?

Done

2024-11-15 15:38 UTC, bittremieux requested changes
Some comments.

In addition, the averaging implementation seems a bit complex at certain points, with creating empty lists of NumPy arrays that are grown iteratively. This is not really optimal; maybe there are some possibilities to still simplify that a bit.

2024-11-15 15:38 UTC, bittremieux commented on falcon/cluster/cluster.py
> +        if std == 0:
**todo:** This should take floating point imprecision into account.

2024-11-15 15:38 UTC, bittremieux commented on falcon/cluster/cluster.py
> +    while len(intensities) > 2:
**thought:** Interesting, I didn't know this was performed iteratively. Don't you progressively remove a bunch of peaks that way?

2024-11-15 15:38 UTC, bittremieux commented on falcon/cluster/cluster.py
> +        mz[idx] = min_mz + (bin_idx * bin_size) + (bin_size / 2)
**thought:** Is this what the algorithm from the paper does? I'd think that taking the average of the m/z values might be better. That would better capture if the m/z's are not evenly distributed over the bin.

2024-11-15 15:38 UTC, bittremieux commented on falcon/config.py
> +            "--n_min",
**todo:** These parameter names can be a bit more descriptive.

2024-11-15 15:38 UTC, bittremieux commented on falcon/cluster/cluster.py
> +        "cluster_size",
**todo:** I don't think this is used for the algorithm, right? In that case we don't need to store this information.

2025-01-06 09:11 UTC, Janne98 commented on falcon/cluster/cluster.py
> +    while len(intensities) > 2:
Yes, this is how they describe it in the paper

2026-06-09 04:45 UTC, Janne98 commented
closing because changes are already in `feature/fast-clustering` branch.

2026-06-09 04:45 UTC, closed without merging